package server

import (
	"fmt"
	"os"
	"strings"
	"time"
)

func WriteEula() error {
    content := "# Generated by Nether\n# https://aka.ms/MinecraftEULA\neula=true\n"
    return os.WriteFile("eula.txt", []byte(content), 0644)
}

func WriteConfig(serverType, version string) error {
    content := fmt.Sprintf(`# Nether server config
type = "%s"
version = "%s"
created = "%s"
`, serverType, version, time.Now().Format(time.RFC3339))
    return os.WriteFile("nether.toml", []byte(content), 0644)
}

var DefaultJVMFlags = []string{
	"-XX:+AlwaysPreTouch",
	"-XX:+DisableExplicitGC",
	"-XX:+ParallelRefProcEnabled",
	"-XX:+PerfDisableSharedMem",
	"-XX:+UnlockExperimentalVMOptions",
	"-XX:+UseG1GC",
	"-XX:G1HeapRegionSize=8M",
	"-XX:G1HeapWastePercent=5",
	"-XX:G1MaxNewSizePercent=40",
	"-XX:G1MixedGCCountTarget=4",
	"-XX:G1MixedGCLiveThresholdPercent=90",
	"-XX:G1NewSizePercent=30",
	"-XX:G1RSetUpdatingPauseTimePercent=5",
	"-XX:G1ReservePercent=20",
	"-XX:InitiatingHeapOccupancyPercent=15",
	"-XX:MaxGCPauseMillis=200",
	"-XX:MaxTenuringThreshold=1",
	"-XX:SurvivorRatio=32",
	"-Dusing.aikars.flags=https://mcflags.emc.gs",
	"-Daikars.new.flags=true",
}

func WriteStartScript(minRAM, maxRAM string) error {
	flagLine := strings.Join(DefaultJVMFlags, " ")

	shContent := fmt.Sprintf("#!/usr/bin/env sh\n\n%s -Xms%s -Xmx%s %s -jar server.jar --nogui\n", bundledJavaRef(), minRAM, maxRAM, flagLine)
	batContent := fmt.Sprintf("@echo off\r\n\r\njava\\bin\\java.exe -Xms%s -Xmx%s %s -jar server.jar --nogui\r\n", minRAM, maxRAM, flagLine)

	if err := os.WriteFile("run.sh", []byte(shContent), 0755); err != nil {
		return err
	}
	return os.WriteFile("run.bat", []byte(batContent), 0755)
}

func WriteServerProperties(port int) error {
	content := fmt.Sprintf("server-port=%d\n", port)
	return os.WriteFile("server.properties", []byte(content), 0644)
}
